"""Does a file's own header claim a generator wrote it?

Split from `_discovery` at this project's 500-line file gate, which the
helpers extracted from `discover` pushed it past — the gate doing its job
on a change to the tool, as it did for `cli`, `_arguments` and
`docs/language-support.md` before it.

The seam is real rather than arithmetic. Everything here reads **one
file's** leading comment block and decides whether it announces itself as
generated; nothing here walks a tree, opens a manifest, or knows what a
directory is. `_discovery` imports this and this never reaches back.

The banner vocabulary is passed in rather than imported, so this module
answers "does this header declare one of these phrases" and `_discovery`
keeps ownership of which phrases matter — which also keeps the import
one-way.
"""
from __future__ import annotations

import os
import re
from pathlib import Path

from ._operator_reads import open_regular_file

# Whatever a language uses to open a comment, plus decoration a generator
# may pad the line with: `#`, `//`, `*`, `/*`, `!`, `--`, `<!--`, `;`, and
# the emoji rules some tools draw. `@` is spared, or `# @generated` would
# strip to `generated` and the most standard banner of all would never
# match — which it did not, until a test caught it.
COMMENT_LEAD = re.compile(r"^[^\w@]*")

# A line ending here finished its thought. One ending in a bare word did
# not, and whatever follows is a continuation rather than a declaration.
SENTENCE_END = (".", "!", "?", "*/", "-->", ":")

# A finished sentence *inside* a line. Text before a banner containing one
# of these means the banner is a clause in someone's prose.
SENTENCE_BREAKS = (". ", "! ", "? ")
BANNER_LINES = 20


def banner_says_generated(
    path: Path, banners: tuple[str, ...]
) -> str | None:
    """The banner text, if the head of this file carries one.

    The head only, so this stays cheap on a large tree — but read
    *through* a checked handle rather than by name, so a FIFO refuses
    instead of stopping the audit dead (D145). `path.open()` on one waits
    for a writer that never comes, and the previous `except OSError`
    could not have caught that: there is no error to catch, only a
    process that never returns.
    """
    try:
        handle = open_regular_file(
            path,
            "Banner detection reads the head of a discovered file; a "
            "device, socket or FIFO would block the audit rather than "
            "declare itself generated.",
        )
    except OSError:
        return None
    try:
        with os.fdopen(handle, "r", encoding="utf-8", errors="replace", closefd=False) as opened:
            head = "".join(next(opened, "") for _ in range(BANNER_LINES)).lower()
    finally:
        os.close(handle)
    previous: str | None = None
    for raw in head.splitlines():
        stripped = COMMENT_LEAD.sub("", raw).strip()
        if not stripped:
            # Pure decoration — a rule of asterisks, a row of emoji. Not
            # content, and not a sentence the next line continues.
            continue
        for banner in banners:
            if declares(stripped, banner, previous):
                return f"banner {banner!r} in the first {BANNER_LINES} lines"
        previous = stripped
    return None


def declares(line: str, banner: str, previous: str | None) -> bool:
    """Whether this line *claims* the file is generated, rather than mentioning it.

    Three real cases, and the false positive that forced the distinction:

    - curl: `/*** Sample code generated by the curl command line tool ***`
      — the banner is the first thing the file says.
    - transformers: `#   This file was automatically generated from ...`,
      after a row of emoji, which is decoration rather than content.
    - material-ui, hand-written, and wrongly removed from its own audit:

          * WARNING: Don't import this directly. It's imported by the
            code generated by `@mui/babel-plugin`.

      Here the phrase sits on the first content line too, but *after* a
      finished sentence — it is the object of "imported by the", talking
      about a generator's output somewhere else.

    So the test is position, not presence: a declaration comes before the
    prose. Nothing that reads like a completed sentence may precede it,
    on this line or the one above.
    """
    index = line.find(banner)
    if index < 0:
        return False
    if any(mark in line[:index] for mark in SENTENCE_BREAKS):
        # A sentence finished before the phrase, so the phrase continues
        # that sentence instead of opening a declaration.
        return False
    if previous is None:
        return True
    # On a later line the phrase must lead it, and the line above must
    # have finished its thought rather than run on into this one.
    return index == 0 and previous.endswith(SENTENCE_END)
