"""What is in this tree, and whose code it is — one pass, before anything else.

Nothing looked at the repository before deciding what to run and what to
score, and two defects came out of that gap.

**Tools claimed coverage of absent languages.** `kilo` is a single C
file. complexipy, mypy, pydocstyle, radon, ruff and vulture all ran,
produced nothing between them, and the coverage section reported
`documentation`, `style`, `types` and `dead-code` as examined. A tool
that ran over zero applicable files examined nothing; saying otherwise
is absence-as-value in the section written to prevent it.

**Other people's code was scored as the team's own.** 10,759 generated
icon wrappers in `packages/mui-icons-material/lib/` entered the
calibration corpus and moved `CALIBRATION_C` from 2.6279 to 2.6414.
5,090 of whisper.cpp's findings are in `ggml/`, synced from another
repository. 16,719 of lapack's are in `TESTING/`.

**Classification is by evidence the repository provides, never by a list
of names.** The name list is precisely what failed: `vendor/` and
`third_party/` were excluded by default and `ggml/` was not, so a
vendored tree counted as first-party because of what its authors called
it. Every rule here points at something checkable — a generation banner,
a build script that deletes and rewrites a directory, a `.gitmodules`
entry, a sync script named for the directory it overwrites — and records
that evidence beside the verdict so a reader can disagree with it.

Where there is no evidence, the answer is first-party. This module
removes code from someone's audit, so a false positive silently deletes
their work from their own report; the bias is deliberately toward
leaving code in.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from enum import StrEnum
from pathlib import Path
from typing import Any

from ._metrics_types import KNOWN_SOURCE_SUFFIXES, is_test_path
from .metrics import is_excluded

# The inventory names languages the way a person does; the analyzer
# catalog names them the way its source database does. Mapped explicitly
# rather than lowercased and hoped over: `C++` -> `cpp` and `C#` ->
# `csharp` do not fall out of any transformation, and comparing the two
# vocabularies directly would find no overlap and mark every C++ tool
# inapplicable. The same defect as concerns against concepts, which made
# two dimensions read as unexamined the day they were split apart.
# `test_every_language_the_inventory_names_maps_to_the_catalogs_vocabulary`
# holds this complete.
CATALOG_LANGUAGE: dict[str, str] = {
    "Python": "python", "JavaScript": "javascript", "TypeScript": "typescript",
    "Java": "java", "Kotlin": "kotlin", "Scala": "scala",
    "C": "c", "C++": "cpp", "C#": "csharp", "F#": "fsharp", "Visual Basic": "visualbasic",
    "Go": "go", "Rust": "rust", "Swift": "swift", "Objective-C": "objectivec",
    "Ruby": "ruby", "PHP": "php", "Perl": "perl", "Lua": "lua", "R": "r",
    "Julia": "julia", "Dart": "dart", "Elixir": "elixir", "Erlang": "erlang",
    "Haskell": "haskell", "OCaml": "ocaml", "Clojure": "clojure", "Fortran": "fortran",
    "Shell": "shell", "PowerShell": "powershell", "SQL": "sql", "Groovy": "groovy",
    "Vue": "vue", "Svelte": "svelte", "Zig": "zig", "Nim": "nim", "Crystal": "crystal",
    "D": "d", "Ada": "ada",
}


class Provenance(StrEnum):
    """Whose code a file is, which decides whether it reaches the score."""

    FIRST_PARTY = "first-party"
    TEST = "test"
    GENERATED = "generated"
    VENDORED = "vendored"


# A banner in the head of a file is the one generation signal that crosses
# ecosystems: protoc, thrift, openapi, swagger, sqlc, Go's stringer and
# Rust's bindgen all write one.
#
# It must *open* a comment line. A substring match classified
# material-ui's hand-written `formatMuiErrorMessage.ts` as generated,
# because its docstring says "It's imported by the code generated by
# `@mui/babel-plugin`" — prose *about* generated code, mid-sentence.
# Removing a team's own file from their own audit is the worse direction
# of error, so the phrase has to lead the line rather than appear in it.
GENERATION_BANNERS: tuple[str, ...] = (
    "@generated",
    "code generated by",
    "do not edit",
    "autogenerated",
    "auto-generated",
    "automatically generated",
    "generated by the protocol buffer compiler",
)

# Whatever a language uses to open a comment, plus decoration a generator
# may pad the line with: `#`, `//`, `*`, `/*`, `!`, `--`, `<!--`, `;`, and
# the emoji rules some tools draw. `@` is spared, or `# @generated` would
# strip to `generated` and the most standard banner of all would never
# match — which it did not, until a test caught it.
COMMENT_LEAD = re.compile(r"^[^\w@]*")

# A line ending here finished its thought. One ending in a bare word did
# not, and whatever follows is a continuation rather than a declaration.
SENTENCE_END = (".", "!", "?", "*/", "-->", ":")

# A finished sentence *inside* a line. Text before a banner containing one
# of these means the banner is a clause in someone's prose.
SENTENCE_BREAKS = (". ", "! ", "? ")
BANNER_LINES = 20

# Filename shapes that are generated by convention across a whole
# toolchain. Narrow on purpose: each is a shape no human writes by hand.
GENERATED_NAME_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\.pb\.(go|cc|h)$"),
    re.compile(r"_pb2(_grpc)?\.py$"),
    re.compile(r"\.g\.dart$"),
    re.compile(r"\.generated\.[a-z]+$"),
    re.compile(r"\.designer\.cs$", re.IGNORECASE),
    re.compile(r"_generated\.go$"),
)

# `rimraf lib && ...` in a package's own scripts. A directory the project
# deletes and rebuilds is build output by its own declaration — the only
# thing that identifies material-ui's icon library, which carries no
# banner and lives in a directory called `lib`.
DELETES_DIRECTORY = re.compile(r"(?:rimraf|rm\s+-rf|rm\s+-fr)\s+([\w./-]+)")

# `scripts/sync-ggml.sh` maintains `ggml/`. A script whose job is to
# overwrite a directory from upstream says that directory is not this
# project's work.
SYNC_SCRIPT = re.compile(r"^sync[-_]([\w.-]+?)(?:\.[a-z]+)?$")


@dataclass
class Inventory:
    """What the tree contains, and the evidence behind every judgment."""

    languages: dict[str, int] = field(default_factory=dict)
    provenance: dict[str, Provenance] = field(default_factory=dict)
    # One entry per non-first-party path, each naming what proved it.
    classifications: list[dict[str, str]] = field(default_factory=list)
    # Directories proved generated or vendored, kept from the pass that
    # found them so consumers can exclude a tree by naming it once
    # instead of naming its 10,759 files.
    directories: dict[str, str] = field(default_factory=dict)

    def not_ours(self) -> set[str]:
        """Relative paths whose code the team did not write."""
        return {
            path for path, verdict in self.provenance.items()
            if verdict in (Provenance.GENERATED, Provenance.VENDORED)
        }

    def exclusions(self) -> tuple[str, ...]:
        """What to keep an analyzer away from: directories, then strays.

        Directories first and files only where no directory covers them.
        A banner-generated `pb2.py` sitting beside hand-written code
        cannot be excluded by its directory without taking the
        hand-written code with it, so it is named on its own; everything
        under a classified tree is covered by the tree.
        """
        directories = tuple(sorted(self.directories))
        strays = tuple(sorted(
            path for path in self.not_ours()
            if not any(_under(path, directory) for directory in directories)
        ))
        return directories + strays

    def speaks(self, language: str) -> bool:
        return self.languages.get(language, 0) > 0

    def speaks_any(self, languages: tuple[str, ...]) -> bool:
        """Whether any of a tool's languages is present.

        Any, not all: lizard reads a dozen languages and must not be
        excluded from a C repository for the absence of Kotlin.
        """
        return any(self.speaks(name) for name in languages)

    def catalog_slugs(self) -> set[str]:
        """The languages present, in the analyzer catalog's vocabulary."""
        return {CATALOG_LANGUAGE[name] for name in self.languages if name in CATALOG_LANGUAGE}

    def applicable(self, tool_languages: object) -> bool:
        """Whether a catalog tool has any input in this tree.

        Unknown or empty language lists mean applicable. Suppressing a
        tool removes real evidence from a report, so the doubt runs
        toward running it: an inapplicable verdict has to be positively
        supported by a language list that shares nothing with the tree.
        """
        if not isinstance(tool_languages, (list, tuple)) or not tool_languages:
            return True
        present = self.catalog_slugs()
        if not present:
            # Nothing recognised in the tree at all — this cannot be the
            # evidence for excluding anything.
            return True
        return bool(present & {str(name).lower() for name in tool_languages})

    def provenance_of(self, relative_path: str) -> Provenance:
        return self.provenance.get(relative_path, Provenance.FIRST_PARTY)

    def counts(self) -> dict[str, int]:
        """How many files of each provenance, for the report summary."""
        tally = dict.fromkeys((p.value for p in Provenance), 0)
        for value in self.provenance.values():
            tally[value.value] += 1
        return tally


def _banner_says_generated(path: Path) -> str | None:
    """The banner text, if the head of this file carries one."""
    try:
        with path.open(encoding="utf-8", errors="replace") as handle:
            head = "".join(next(handle, "") for _ in range(BANNER_LINES)).lower()
    except OSError:
        return None
    previous: str | None = None
    for raw in head.splitlines():
        stripped = COMMENT_LEAD.sub("", raw).strip()
        if not stripped:
            # Pure decoration — a rule of asterisks, a row of emoji. Not
            # content, and not a sentence the next line continues.
            continue
        for banner in GENERATION_BANNERS:
            if _declares(stripped, banner, previous):
                return f"banner {banner!r} in the first {BANNER_LINES} lines"
        previous = stripped
    return None


def _declares(line: str, banner: str, previous: str | None) -> bool:
    """Whether this line *claims* the file is generated, rather than mentioning it.

    Three real cases, and the false positive that forced the distinction:

    - curl: `/*** Sample code generated by the curl command line tool ***`
      — the banner is the first thing the file says.
    - transformers: `#   This file was automatically generated from ...`,
      after a row of emoji, which is decoration rather than content.
    - material-ui, hand-written, and wrongly removed from its own audit:

          * WARNING: Don't import this directly. It's imported by the
            code generated by `@mui/babel-plugin`.

      Here the phrase sits on the first content line too, but *after* a
      finished sentence — it is the object of "imported by the", talking
      about a generator's output somewhere else.

    So the test is position, not presence: a declaration comes before the
    prose. Nothing that reads like a completed sentence may precede it,
    on this line or the one above.
    """
    index = line.find(banner)
    if index < 0:
        return False
    if any(mark in line[:index] for mark in SENTENCE_BREAKS):
        # A sentence finished before the phrase, so the phrase continues
        # that sentence instead of opening a declaration.
        return False
    if previous is None:
        return True
    # On a later line the phrase must lead it, and the line above must
    # have finished its thought rather than run on into this one.
    return index == 0 and previous.endswith(SENTENCE_END)


def _generated_directories(root: Path, excludes: tuple[str, ...]) -> dict[str, str]:
    """Directories a `package.json` script deletes and rebuilds."""
    found: dict[str, str] = {}
    for manifest in root.rglob("package.json"):
        relative = manifest.relative_to(root).as_posix()
        if is_excluded(relative, list(excludes)):
            continue
        try:
            scripts = json.loads(manifest.read_text(encoding="utf-8")).get("scripts", {})
        except (OSError, ValueError, AttributeError):
            continue
        if not isinstance(scripts, dict):
            continue
        for name, command in scripts.items():
            for target in DELETES_DIRECTORY.findall(str(command)):
                cleaned = target.strip("./")
                if not cleaned or cleaned.startswith(".."):
                    continue
                directory = (manifest.parent / cleaned).relative_to(root).as_posix()
                found.setdefault(
                    directory,
                    f"deleted and rebuilt by `{name}` in {relative}: "
                    f"`{str(command)[:60]}`",
                )
    return found


def _vendored_directories(root: Path) -> dict[str, str]:
    """Directories the repository says belong to someone else."""
    found: dict[str, str] = {}

    modules = root / ".gitmodules"
    if modules.exists():
        try:
            text = modules.read_text(encoding="utf-8", errors="replace")
        except OSError:
            text = ""
        for entry in re.finditer(r"^\s*path\s*=\s*(.+?)\s*$", text, re.MULTILINE):
            found.setdefault(entry.group(1).strip("./"), "declared a submodule in .gitmodules")

    # A script named for the directory it overwrites from upstream.
    for script in root.rglob("sync-*"):
        if not script.is_file():
            continue
        match = SYNC_SCRIPT.match(script.stem)
        if not match:
            continue
        candidate = match.group(1)
        target = root / candidate
        if target.is_dir():
            found.setdefault(
                candidate,
                f"maintained from upstream by {script.relative_to(root).as_posix()}",
            )
    return found


def _under(relative: str, directory: str) -> bool:
    return relative == directory or relative.startswith(f"{directory}/")


# `is_test_path` matches `test` and `tests` exactly, so lapack's
# `TESTING/` fell through and 16,719 findings scored as production code.
# Checked as a whole path segment, never a substring: `src/attestation/`
# is not test code.
TEST_DIRECTORY_NAMES = frozenset({"testing", "tests", "test", "__tests__", "spec", "specs"})


def _is_test(relative: str) -> bool:
    if is_test_path(relative):
        return True
    segments = relative.lower().split("/")[:-1]
    return any(segment in TEST_DIRECTORY_NAMES for segment in segments)


def discover(root: Path, config: dict[str, Any]) -> Inventory:
    """One pass over the tree: what languages, and whose code.

    Never raises. An unreadable manifest or script is skipped rather than
    ending the audit — a tree this cannot fully classify still yields a
    partial inventory, and a partial inventory is better than treating
    everything as first-party silently.
    """
    excludes = tuple((config.get("paths") or {}).get("exclude_patterns", ()))
    generated_dirs = _generated_directories(root, excludes)
    vendored_dirs = _vendored_directories(root)

    inventory = Inventory()
    inventory.directories = {
        **{name: Provenance.VENDORED.value for name in vendored_dirs},
        **{name: Provenance.GENERATED.value for name in generated_dirs
           if name not in vendored_dirs},
    }
    seen_directories: set[tuple[str, str]] = set()
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix not in KNOWN_SOURCE_SUFFIXES:
            continue
        relative = path.relative_to(root).as_posix()
        if is_excluded(relative, list(excludes)):
            continue

        verdict, evidence, owner = _classify(
            path, relative, generated_dirs, vendored_dirs)
        if verdict is Provenance.FIRST_PARTY:
            language = KNOWN_SOURCE_SUFFIXES[path.suffix]
            inventory.languages[language] = inventory.languages.get(language, 0) + 1
        inventory.provenance[relative] = verdict
        if verdict is Provenance.FIRST_PARTY or evidence is None:
            continue
        # One entry per directory rather than per file: 10,759 identical
        # rows for material-ui's icons would bury everything else.
        key = (owner or relative, verdict.value)
        if key in seen_directories:
            continue
        seen_directories.add(key)
        inventory.classifications.append(
            {"path": owner or relative, "provenance": verdict.value, "evidence": evidence})
    return inventory


def _classify(
    path: Path, relative: str,
    generated_dirs: dict[str, str], vendored_dirs: dict[str, str],
) -> tuple[Provenance, str | None, str | None]:
    """One file's provenance, the evidence for it, and what it belongs to.

    Order is deliberate. Vendored beats generated beats test: a generated
    file inside a vendored tree is somebody else's generated file, and
    reporting it as ours-but-generated would be half right in the way
    that misleads.
    """
    for directory, evidence in vendored_dirs.items():
        if _under(relative, directory):
            return Provenance.VENDORED, evidence, directory
    for directory, evidence in generated_dirs.items():
        if _under(relative, directory):
            return Provenance.GENERATED, evidence, directory
    for pattern in GENERATED_NAME_PATTERNS:
        if pattern.search(path.name):
            return Provenance.GENERATED, f"filename matches {pattern.pattern}", relative
    banner = _banner_says_generated(path)
    if banner:
        return Provenance.GENERATED, banner, relative
    if _is_test(relative):
        return Provenance.TEST, None, None
    return Provenance.FIRST_PARTY, None, None
