sonar.projectKey=marshallguillory86_maintainability-agent
sonar.organization=marshallguillory86
sonar.projectName=maintainability-agent

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.exclusions=build/**,dist/**,*.egg-info/**,.venv/**,venv/**
