"""What is in this tree, and whose code is it — the inventory pass.

Two defects, both measured on the validation sample and the calibration
corpus, both caused by the same absence: **nothing looks at the
repository before deciding what to run and what to score.**

**Tools claim coverage of languages that are not present.** `kilo` is one
C file. complexipy, mypy, pydocstyle, radon, ruff and vulture all ran,
produced zero measurements and zero findings between them, and the
coverage section reported `documentation`, `style`, `types` and
`dead-code` as *examined*. Identical on gson and ripgrep. "Ran and found
nothing" is a result when a tool had input and a lie when it had none —
absence-as-value, arriving in the section written to prevent it.

**Generated and vendored code is scored as the team's own.** Adding
`.mjs` to the include list pulled 10,759 files from
`packages/mui-icons-material/lib/` into the corpus — six-line SVG icon
wrappers, one per icon, written by `builder.mjs`. They dropped
material-ui's duplication from 3.729 to 2.321 and moved `CALIBRATION_C`
from 2.6279 to 2.6414. On whisper.cpp, 5,090 of roughly 7,000 findings
are in `ggml/`, a library synced from another repository by
`scripts/sync-ggml.sh`. On lapack, 16,719 findings are in `TESTING/`,
which `is_test_path` misses because it matches `test` and `tests` but
not `testing`.

The rule these tests hold:

    Classification is by evidence the repository itself provides, never
    by a list of directory names.

The name list is what already failed. `vendor/` and `third_party/` were
in the default exclusions and `ggml/` was not, so a vendored tree
counted as first-party because of what its authors happened to call it.
Every rule below points at something checkable: a generation banner, a
build script that deletes and rewrites a directory, a submodule entry, a
sync script named for the directory it maintains.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from maintainability_audit._discovery import Provenance, discover


def _repo(root: Path, files: dict[str, str]) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    subprocess.run(["git", "init", "-q", str(root)], check=True)
    for name, body in files.items():
        target = root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
    return root


# --------------------------------------------------------------------
# The language inventory, and what it is for
# --------------------------------------------------------------------


def test_the_inventory_counts_the_languages_actually_present(tmp_path: Path) -> None:
    """The first question about a repository, which nothing was asking."""
    root = _repo(tmp_path / "poly", {
        **{f"src/a{n}.c": "int f(void) { return 0; }\n" for n in range(7)},
        **{f"src/b{n}.h": "int f(void);\n" for n in range(3)},
        **{f"tool/x{n}.py": "def f():\n    return 1\n" for n in range(2)},
    })

    inventory = discover(root, {})

    assert inventory.languages == {"C": 10, "Python": 2}


def test_a_tool_for_a_language_that_is_absent_is_not_applicable(tmp_path: Path) -> None:
    """The kilo case: six Python-only tools, one C file, four concerns "covered".

    A tool that ran over zero applicable files examined nothing. Saying
    otherwise is the same collapse the coverage section exists to
    prevent, one level further out.
    """
    root = _repo(tmp_path / "conly", {"kilo.c": "int main(void) { return 0; }\n"})

    inventory = discover(root, {})

    assert inventory.speaks("Python") is False
    assert inventory.speaks("C") is True


def test_a_tool_covering_any_present_language_is_applicable(tmp_path: Path) -> None:
    """Partial overlap is still overlap.

    lizard reads C, Java, Go, Rust and more. On a mixed tree it must not
    be excluded because one of its languages is missing.
    """
    root = _repo(tmp_path / "mixed", {
        "a.c": "int f(void) { return 0; }\n",
        "b.py": "def f():\n    return 1\n",
    })

    inventory = discover(root, {})

    assert inventory.speaks_any(("Java", "Go", "C")) is True
    assert inventory.speaks_any(("Java", "Go", "Rust")) is False


# --------------------------------------------------------------------
# Provenance: whose code is this
# --------------------------------------------------------------------


def test_a_generation_banner_marks_a_file_generated(tmp_path: Path) -> None:
    """The standard signal, and the only one that crosses ecosystems."""
    root = _repo(tmp_path / "gen", {
        "api/schema.py": "# Code generated by protoc. DO NOT EDIT.\n\ndef f():\n    return 1\n",
        "api/handwritten.py": "def g():\n    return 2\n",
    })

    inventory = discover(root, {})

    assert inventory.provenance_of("api/schema.py") == Provenance.GENERATED
    assert inventory.provenance_of("api/handwritten.py") == Provenance.FIRST_PARTY


def test_a_directory_a_build_script_deletes_and_rewrites_is_generated(tmp_path: Path) -> None:
    """The material-ui case, and the reason a name list cannot do this job.

    `packages/mui-icons-material/lib/` holds 10,759 six-line icon
    wrappers with no banner of any kind. What identifies them is the
    package's own `package.json`:

        "build:lib:clean": "rimraf lib && pnpm build:lib && ..."

    A directory the project deletes and regenerates is build output by
    the project's own declaration. `lib/` is an ordinary source
    directory in most repositories, so nothing about the *name* could
    have told us.
    """
    root = _repo(tmp_path / "mui", {
        "packages/icons/package.json": json.dumps(
            {"name": "icons", "scripts": {"build:lib:clean": "rimraf lib && build --flat"}}),
        "packages/icons/lib/IconA.mjs": "export default 1;\n",
        "packages/icons/lib/IconB.mjs": "export default 2;\n",
        "packages/icons/src/builder.mjs": "export function build() { return 3; }\n",
    })

    inventory = discover(root, {})

    assert inventory.provenance_of("packages/icons/lib/IconA.mjs") == Provenance.GENERATED
    assert inventory.provenance_of("packages/icons/src/builder.mjs") == Provenance.FIRST_PARTY
    assert any("rimraf" in item["evidence"] for item in inventory.classifications)


def test_a_submodule_directory_is_vendored(tmp_path: Path) -> None:
    """`.gitmodules` is the repository stating the code is someone else's."""
    root = _repo(tmp_path / "sub", {
        ".gitmodules": '[submodule "deps/lib"]\n\tpath = deps/lib\n\turl = https://x/y\n',
        "deps/lib/core.c": "int f(void) { return 0; }\n",
        "src/main.c": "int main(void) { return 0; }\n",
    })

    inventory = discover(root, {})

    assert inventory.provenance_of("deps/lib/core.c") == Provenance.VENDORED
    assert inventory.provenance_of("src/main.c") == Provenance.FIRST_PARTY


def test_a_directory_maintained_by_a_sync_script_is_vendored(tmp_path: Path) -> None:
    """The whisper.cpp case: 5,090 findings in a tree copied from elsewhere.

    `ggml/` is not a submodule and is not named `vendor/`. What says it
    is not whisper.cpp's code is `scripts/sync-ggml.sh` beside a
    `sync-ggml.last` recording the upstream commit — a directory with a
    script whose whole job is to overwrite it from another repository.
    """
    root = _repo(tmp_path / "whisper", {
        "scripts/sync-ggml.sh": "#!/bin/sh\ncp -r ../ggml/src ./ggml/\n",
        "ggml/src/core.c": "int f(void) { return 0; }\n",
        "src/main.c": "int main(void) { return 0; }\n",
    })

    inventory = discover(root, {})

    assert inventory.provenance_of("ggml/src/core.c") == Provenance.VENDORED
    assert inventory.provenance_of("src/main.c") == Provenance.FIRST_PARTY


def test_an_upper_case_testing_directory_is_test_code(tmp_path: Path) -> None:
    """lapack's `TESTING/` — 16,719 findings scored as production.

    `is_test_path` lowercases and then matches `test` and `tests`
    exactly, so `testing` fell through. Fortran convention, not an edge
    case worth ignoring.
    """
    root = _repo(tmp_path / "lapack", {
        "SRC/dgelss.f": "      SUBROUTINE DGELSS\n      END\n",
        "TESTING/MATGEN/clatm2.f": "      SUBROUTINE CLATM2\n      END\n",
    })

    inventory = discover(root, {})

    assert inventory.provenance_of("TESTING/MATGEN/clatm2.f") == Provenance.TEST
    assert inventory.provenance_of("SRC/dgelss.f") == Provenance.FIRST_PARTY


def test_every_classification_carries_the_evidence_for_it(tmp_path: Path) -> None:
    """A classification nobody can check is a guess with better manners.

    The name list this replaces could not explain itself: `ggml/` was
    first-party because it was not called `vendor/`, and no output said
    so. Every non-first-party classification names the file or script
    that proves it.
    """
    root = _repo(tmp_path / "evidence", {
        ".gitmodules": '[submodule "deps/lib"]\n\tpath = deps/lib\n\turl = https://x/y\n',
        "deps/lib/core.c": "int f(void) { return 0; }\n",
        "gen/out.py": "# @generated\ndef f():\n    return 1\n",
    })

    inventory = discover(root, {})

    for item in inventory.classifications:
        assert item["provenance"] in {p.value for p in Provenance}
        assert item["evidence"], f"{item['path']} classified with no evidence"
        assert item["path"]


def test_an_unremarkable_repository_is_all_first_party(tmp_path: Path) -> None:
    """The check must not fire on the case it does not describe.

    Every rule here excludes code from someone's score. A false positive
    is not a cosmetic problem: it silently removes the team's own work
    from their audit, which is the opposite failure and just as bad.
    """
    root = _repo(tmp_path / "plain", {
        "src/lib.py": "def f():\n    return 1\n",
        "src/util.py": "def g():\n    return 2\n",
        "lib/helper.py": "def h():\n    return 3\n",
        "package.json": json.dumps({"name": "x", "scripts": {"test": "pytest"}}),
    })

    inventory = discover(root, {})

    assert inventory.classifications == []
    assert all(inventory.provenance_of(p) == Provenance.FIRST_PARTY
               for p in ("src/lib.py", "src/util.py", "lib/helper.py"))


# --------------------------------------------------------------------
# What the inventory changes downstream
# --------------------------------------------------------------------


def test_generated_and_vendored_code_leaves_the_scored_population(tmp_path: Path) -> None:
    """The calibration blocker, reduced.

    10,759 generated icon files moved a corpus constant. Code the team
    did not write must not move their score, in either direction.
    """
    from maintainability_audit.config import load_config
    from maintainability_audit.report import build_report

    body = "def f_%(n)d(value):\n    return value + 1\n"
    root = _repo(tmp_path / "scored", {
        ".gitmodules": '[submodule "deps/lib"]\n\tpath = deps/lib\n\turl = https://x/y\n',
        **{f"src/mod{n}.py": body % {"n": n} for n in range(150)},
        **{f"deps/lib/dep{n}.py": body % {"n": n} for n in range(300)},
        **{f"gen/out{n}.py": "# @generated\n" + body % {"n": n} for n in range(300)},
    })

    report = build_report(root, load_config(None))
    summary = report["summary"]

    assert summary["files_scanned"] == 150, (
        "600 files of other people's code entered the population: "
        f"scanned {summary['files_scanned']}"
    )
    assert summary["generated_files"] == 300
    assert summary["vendored_files"] == 300


@pytest.mark.parametrize(("name", "expected"), [
    ("whisper.cpp", "ggml"),
    ("lapack", "TESTING"),
])
def test_the_sample_repositories_are_classified(name: str, expected: str) -> None:
    """Held against the recorded run, not re-cloned.

    Skipped rather than failed when the sample has not been run: a
    missing artifact is not evidence of correctness either way.
    """
    results = Path(__file__).resolve().parents[1] / "tools" / "validation" / "results.json"
    if not results.exists():
        pytest.skip("validation sample has not been run")
    runs = {r["repo"]: r for r in json.loads(results.read_text(encoding="utf-8"))["runs"]}
    run = runs.get(name)
    if run is None or run.get("classifications") is None:
        pytest.skip(f"{name} has no recorded classifications")

    classified = {item["path"].split("/")[0] for item in run["classifications"]}
    assert expected in classified, (
        f"{name}: {expected}/ is not first-party code and must be classified; "
        f"classified: {sorted(classified)[:8]}"
    )


# --------------------------------------------------------------------
# Tool applicability: the second consumer
# --------------------------------------------------------------------


def test_every_language_the_inventory_names_maps_to_the_catalogs_vocabulary() -> None:
    """Two vocabularies, mapped explicitly rather than compared.

    The inventory says `C++` and `C#`; the catalog says `cpp` and
    `csharp`. Comparing them directly would silently find no overlap and
    mark every C++ tool inapplicable — the same class of bug as concerns
    against concepts, which made `metrics` and `structure` read as
    unexamined the moment the two vocabularies diverged.
    """
    from maintainability_audit._discovery import CATALOG_LANGUAGE
    from maintainability_audit._metrics_types import KNOWN_SOURCE_SUFFIXES

    named = set(KNOWN_SOURCE_SUFFIXES.values())
    unmapped = sorted(name for name in named if name not in CATALOG_LANGUAGE)

    assert not unmapped, (
        f"the inventory can report {unmapped} and no catalog slug is declared for them, "
        "so every tool for those languages would read as inapplicable"
    )


def test_a_python_only_tool_on_a_c_repository_is_not_applicable(tmp_path: Path) -> None:
    """The kilo defect, at its cause.

    Six Python-only tools ran over one C file, produced nothing, and the
    coverage section reported four concerns examined. A tool with no
    input has examined nothing, and the outcome has to say so rather
    than leaving `ran` to be read as coverage.
    """
    from maintainability_audit._analysis import analyze
    from maintainability_audit.config import load_config

    root = _repo(tmp_path / "conly", {"kilo.c": "int main(void) { return 0; }\n"})
    analysis = analyze(root, load_config(None))
    rows = {item.slug: item for item in analysis.coverage if item.tier == "analyzer"}

    assert rows["ruff"].outcome == "not-applicable"
    # The reason names both halves: what the tool reads, and what is here.
    assert "python" in rows["ruff"].detail.lower()
    assert "this tree is C" in rows["ruff"].detail
    assert not rows["ruff"].contributed, "an inapplicable tool covers nothing"
    # lizard reads C, so it is applicable and must be unaffected.
    assert rows["lizard"].outcome != "not-applicable"

    covered = analysis.measured_concepts()
    assert "types" not in covered, "mypy reads only Python; nothing examined types"
    assert "style" not in covered, "ruff and pydocstyle read only Python"
    assert "dead-code" not in covered, "vulture reads only Python"
    # `documentation` stays, and that is correct rather than a leak:
    # multimetric computes a comment ratio on C and produced four
    # measurements here. The filter removes tools with no input, not
    # every tool whose concern looks Python-flavoured.
    assert "documentation" in covered


def test_a_tool_is_applicable_when_any_of_its_languages_is_present(tmp_path: Path) -> None:
    """Partial overlap is overlap; the filter must not over-fire.

    Marking a tool inapplicable suppresses real evidence, so the bias
    runs the other way: present in doubt, absent only when none of the
    tool's languages appear in the tree at all.
    """
    from maintainability_audit._analysis import analyze
    from maintainability_audit.config import load_config

    root = _repo(tmp_path / "mixed", {
        "a.c": "int f(void) { return 0; }\n",
        "b.py": "def f():\n    return 1\n",
    })
    analysis = analyze(root, load_config(None))
    rows = {item.slug: item for item in analysis.coverage if item.tier == "analyzer"}

    assert rows["ruff"].outcome != "not-applicable", "Python is present"
    assert rows["lizard"].outcome != "not-applicable", "C is present"


def test_prose_mentioning_generated_code_is_not_a_generation_banner(tmp_path: Path) -> None:
    """A comment *about* generated code is not a claim to be generated.

    Found in the re-derivation, in material-ui's own source:

        /**
         * WARNING: Don't import this directly. It's imported by the
         * code generated by `@mui/internal-babel-plugin-minify-errors`.

    `formatMuiErrorMessage.ts` is hand-written and was classified
    generated, which silently removes a team's own file from their own
    audit — the exact failure this module's docstring warns about, found
    on its first real run.

    A generation banner is a declaration a tool writes at the head of a
    file, so it *opens* a comment line. It does not appear as a clause
    in the middle of a sentence of prose.
    """
    root = _repo(tmp_path / "banner", {
        "src/about.ts": (
            "/**\n * WARNING: Don't import this directly. It's imported by the\n"
            " * code generated by `@mui/babel-plugin`. Do not edit that output.\n */\n"
            "export function f() { return 1; }\n"
        ),
        "src/real.py": (
            "#\n#   This file was automatically generated from modular_x.py.\n"
            "#   Do NOT edit this file manually.\n#\ndef f():\n    return 1\n"
        ),
        "src/c_style.c": "/* Code generated by protoc. DO NOT EDIT. */\nint f(void) { return 0; }\n",
    })

    inventory = discover(root, {})

    assert inventory.provenance_of("src/about.ts") == Provenance.FIRST_PARTY, (
        "prose mentioning generated code is not a generation banner"
    )
    assert inventory.provenance_of("src/real.py") == Provenance.GENERATED
    assert inventory.provenance_of("src/c_style.c") == Provenance.GENERATED
