"""Analyzers skip the files the score skips.

`report.build_report` already drops `Provenance.GENERATED` and
`Provenance.VENDORED` before `collect_metrics` — 10,759 generated icon
files moved a calibration constant once, and code the team did not write
must not move their score in either direction.

The analyzer pool never learned that. `_analysis.analyze` calls
`discover()` and uses the inventory for *language applicability only*;
tool invocations get `paths.exclude_patterns` and nothing else. So a
repository whose vendored tree is not in `exclude_patterns` has it
skipped by the built-in scan and walked by every analyzer, and the
findings come back attributed to the user.

Two halves, because a tool is not obliged to honour its own exclude flag:

- **The invocation** names the classified directories, so a tool that
  does honour exclusions never opens them.
- **The output** is filtered by provenance, so a tool that ignores them
  cannot smuggle the files back in.

Counts are untouched: `summary.generated_files`, `summary.vendored_files`
and `classifications` still report what is there. Not scoring somebody
else's code is not the same as pretending it is absent.
"""
from __future__ import annotations

import json
from pathlib import Path

from maintainability_audit._adapters import exclusions_for
from maintainability_audit._analysis import ours_only
from maintainability_audit._discovery import Provenance, discover
from maintainability_audit._metric_adapters import expand_files
from maintainability_audit._metrics_types import Finding, Measurement
from maintainability_audit.config import load_config

GENERATED_BANNER = "# @generated by protoc\n\n\ndef stub():\n    return 1\n"


def _tree(root: Path) -> Path:
    """First-party code, a generated directory, a submodule, a banner file."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text("# r\n", encoding="utf-8")

    (root / "src").mkdir()
    (root / "src" / "app.py").write_text("def ours():\n    return 1\n", encoding="utf-8")

    # A directory a package.json script deletes and rebuilds.
    (root / "package.json").write_text(
        json.dumps({"scripts": {"build": "rm -rf lib && tsc"}}), encoding="utf-8"
    )
    (root / "lib").mkdir()
    (root / "lib" / "bundle.js").write_text("export const a = 1;\n", encoding="utf-8")

    # A directory the repository declares as somebody else's.
    (root / ".gitmodules").write_text(
        '[submodule "ggml"]\n\tpath = ggml\n\turl = https://example.invalid\n',
        encoding="utf-8",
    )
    (root / "ggml").mkdir()
    (root / "ggml" / "core.py").write_text("def theirs():\n    return 2\n", encoding="utf-8")

    # Generated by banner alone, under no classified directory.
    (root / "src" / "pb2.py").write_text(GENERATED_BANNER, encoding="utf-8")
    return root


def _inventory(root: Path):
    return discover(root, load_config(None))


def test_the_fixture_classifies_all_three_kinds(tmp_path: Path) -> None:
    """The premise. Without it every assertion below is vacuous."""
    inventory = _inventory(_tree(tmp_path / "tree"))

    assert inventory.provenance["lib/bundle.js"] is Provenance.GENERATED
    assert inventory.provenance["ggml/core.py"] is Provenance.VENDORED
    assert inventory.provenance["src/pb2.py"] is Provenance.GENERATED
    assert inventory.provenance["src/app.py"] is Provenance.FIRST_PARTY


def test_measurements_from_generated_or_vendored_paths_are_dropped(tmp_path: Path) -> None:
    """A tool that ignored its exclude flag must not reach the report."""
    root = _tree(tmp_path / "tree")
    inventory = _inventory(root)
    measurements = [
        Measurement("cyclomatic_complexity", "ccn", 4.0, "lizard", str(root / "src" / "app.py")),
        Measurement("cyclomatic_complexity", "ccn", 40.0, "lizard", str(root / "lib" / "bundle.js")),
        Measurement("cyclomatic_complexity", "ccn", 40.0, "lizard", str(root / "ggml" / "core.py")),
        Measurement("cyclomatic_complexity", "ccn", 40.0, "lizard", str(root / "src" / "pb2.py")),
    ]

    kept = ours_only(measurements, root, inventory)

    assert [item.path for item in kept] == [str(root / "src" / "app.py")]


def test_findings_from_generated_or_vendored_paths_are_dropped(tmp_path: Path) -> None:
    """Same rule, same reason: the user did not write it."""
    root = _tree(tmp_path / "tree")
    inventory = _inventory(root)
    findings = [
        Finding("dead-code", str(root / "src" / "app.py"), 1, "unused", "vulture"),
        Finding("dead-code", str(root / "ggml" / "core.py"), 1, "unused", "vulture"),
        Finding("dead-code", "src/pb2.py", 1, "unused", "vulture"),
    ]

    kept = ours_only(findings, root, inventory)

    assert [item.path for item in kept] == [str(root / "src" / "app.py")], (
        "a relative path must be matched as readily as an absolute one"
    )


def test_the_invocation_excludes_carry_the_classified_directories(tmp_path: Path) -> None:
    """Directories, not tens of thousands of file paths.

    material-ui's icons are 10,759 files under one directory. Naming the
    directory is what keeps the command line finite.
    """
    inventory = _inventory(_tree(tmp_path / "tree"))

    exclusions = inventory.exclusions()

    assert "lib" in exclusions, f"the generated directory is missing: {exclusions}"
    assert "ggml" in exclusions, f"the vendored directory is missing: {exclusions}"
    assert "lib/bundle.js" not in exclusions, (
        "a file under a classified directory must not be listed separately"
    )


def test_a_banner_only_file_is_excluded_even_with_no_directory(tmp_path: Path) -> None:
    """The case a directory list cannot cover.

    `src/pb2.py` is generated because it says so, and it sits beside
    hand-written code. Excluding its directory would take `src/app.py`
    with it, so the file itself has to be named.
    """
    inventory = _inventory(_tree(tmp_path / "tree"))

    exclusions = inventory.exclusions()

    assert "src/pb2.py" in exclusions
    assert "src" not in exclusions, "excluding the whole directory would drop first-party code"


def test_expand_files_honours_the_inventory_exclusions(tmp_path: Path) -> None:
    """Tools with no exclude flag are filtered by what we name.

    `expand_files` matched on path *parts*, so `vendor` worked and
    `src/pb2.py` did not. A relative path has to be understood too, or
    every no-flag adapter keeps walking the file.
    """
    root = _tree(tmp_path / "tree")
    inventory = _inventory(root)

    # Through `exclusions_for`, not a flat concatenation: merging the two
    # kinds into one sequence is what gave `lib` name semantics.
    named = expand_files(root, exclusions_for(load_config(None), inventory))

    assert any(path.endswith("src/app.py") for path in named), "first-party code was dropped"
    assert not [path for path in named if "pb2.py" in path], "a banner-generated file was named"
    assert not [path for path in named if "/ggml/" in path], "a vendored file was named"
    assert not [path for path in named if "/lib/" in path], "a generated file was named"


def test_the_counts_survive_the_exclusion(tmp_path: Path) -> None:
    """Skipped is not the same as absent.

    Dropping the counts would leave a reader unable to tell a repository
    with no generated code from one where we chose not to score it.
    """
    from maintainability_audit.report import build_report

    root = _tree(tmp_path / "tree")
    summary = build_report(root, load_config(None))["summary"]

    assert summary["generated_files"] >= 2, summary["generated_files"]
    assert summary["vendored_files"] >= 1, summary["vendored_files"]
    assert summary["classifications"], "the evidence for each judgment is still reported"


# --------------------------------------------------------------------
# Two kinds of exclusion, two meanings
# --------------------------------------------------------------------
#
# `node_modules` from `exclude_patterns` is a *name*: drop it wherever it
# appears. `lib` from the inventory is a *path*: one directory, at the
# repository root, proved generated by a build script. Matching the
# second like the first makes `lib` mean "every directory named lib",
# which is the directory-name list ADR 010 rejected — and it silently
# drops first-party `src/lib/owned.py`.


def _lib_tree(root: Path) -> Path:
    """Root `lib/` is generated; `src/lib/` is the team's own code."""
    root.mkdir(parents=True, exist_ok=True)
    (root / "README.md").write_text("# r\n", encoding="utf-8")
    (root / "package.json").write_text(
        json.dumps({"scripts": {"build": "rm -rf lib && tsc"}}), encoding="utf-8"
    )
    (root / "lib").mkdir()
    (root / "lib" / "bundle.js").write_text("export const a = 1;\n", encoding="utf-8")

    (root / "src" / "lib").mkdir(parents=True)
    (root / "src" / "lib" / "owned.py").write_text("def ours():\n    return 1\n", encoding="utf-8")
    (root / "src" / "library.py").write_text("def near():\n    return 2\n", encoding="utf-8")
    (root / "node_modules").mkdir()
    (root / "node_modules" / "dep.js").write_text("export const b = 2;\n", encoding="utf-8")
    return root


def test_a_classified_directory_does_not_drop_a_same_named_one_elsewhere(
    tmp_path: Path,
) -> None:
    """`lib` means the root `lib`, not every directory called lib."""
    root = _lib_tree(tmp_path / "lib-tree")
    inventory = _inventory(root)

    assert inventory.provenance["lib/bundle.js"] is Provenance.GENERATED
    assert inventory.provenance["src/lib/owned.py"] is Provenance.FIRST_PARTY

    named = expand_files(root, exclusions_for(load_config(None), inventory))

    assert any(path.endswith("src/lib/owned.py") for path in named), (
        "first-party src/lib/owned.py was dropped by the root lib/ classification"
    )
    assert any(path.endswith("src/library.py") for path in named), (
        "a prefix match leaked past the directory boundary"
    )
    assert not [path for path in named if path.endswith("lib/bundle.js")], (
        "the generated tree was not excluded"
    )


def test_config_patterns_keep_their_component_meaning(tmp_path: Path) -> None:
    """The operator's `node_modules` still drops it wherever it sits.

    Reinterpreting config patterns as root-relative prefixes would be
    this bug in mirror image: `node_modules/` would stop matching
    `packages/ui/node_modules`.
    """
    root = _lib_tree(tmp_path / "config-tree")
    nested = root / "packages" / "ui" / "node_modules"
    nested.mkdir(parents=True)
    (nested / "dep.js").write_text("export const c = 3;\n", encoding="utf-8")

    named = expand_files(root, exclusions_for(load_config(None), _inventory(root)))

    assert not [path for path in named if "node_modules" in path], (
        "a configured directory name stopped matching below the root"
    )


def test_a_tool_glob_never_receives_a_bare_inventory_token(tmp_path: Path) -> None:
    """`radon -i lib*` would also ignore `library.py` and `src/lib`.

    A tool that takes glob patterns must be handed something that means
    *this tree*, not a token that happens to prefix other names.
    """
    from maintainability_audit._metric_adapters import RadonAdapter

    root = _lib_tree(tmp_path / "glob-tree")
    excludes = exclusions_for(load_config(None), _inventory(root))

    argv = RadonAdapter().invocation(root, excludes=excludes).argv
    patterns = argv[argv.index("-i") + 1].split(",") if "-i" in argv else []

    assert "lib*" not in patterns, (
        f"a bare inventory token reached the glob: {patterns}"
    )
    assert any(pattern.startswith("lib/") for pattern in patterns), (
        f"the generated tree is not excluded from radon at all: {patterns}"
    )


def test_first_party_code_under_a_classified_name_still_reports(tmp_path: Path) -> None:
    """`ours_only` is path-exact and must stay that way."""
    root = _lib_tree(tmp_path / "exact-tree")
    inventory = _inventory(root)
    measurements = [
        Measurement("cyclomatic_complexity", "ccn", 1.0, "radon", str(root / "src" / "lib" / "owned.py")),
        Measurement("cyclomatic_complexity", "ccn", 9.0, "radon", str(root / "lib" / "bundle.js")),
    ]

    kept = [item.path for item in ours_only(measurements, root, inventory)]

    assert kept == [str(root / "src" / "lib" / "owned.py")]


def test_expand_files_states_a_truncation_instead_of_dropping_it_silently(
    tmp_path: Path, caplog,
) -> None:
    """A file list too long for the command line is stated, not silent (#5).

    The old fixed cap of 400 dropped files from any larger tree without a
    word, so the analyzer measured a fraction and the report claimed the
    whole. The budget is now the real argv limit, and a truncation is
    logged rather than hidden.
    """
    from maintainability_audit._metric_adapters import _ARGV_BYTE_BUDGET, expand_files

    small = tmp_path / "small"
    (small / "pkg").mkdir(parents=True)
    for i in range(20):
        (small / "pkg" / f"m{i}.py").write_text("x", encoding="utf-8")
    assert len(expand_files(small, ())) == 20, "a tree under budget keeps every file"

    big = tmp_path / "big"
    (big / "pkg").mkdir(parents=True)
    count = (_ARGV_BYTE_BUDGET // 24) + 500
    for i in range(count):
        (big / "pkg" / f"file_{i:06d}.py").write_text("x", encoding="utf-8")

    import logging
    with caplog.at_level(logging.WARNING, logger="maintainability_audit._metric_adapters"):
        kept = expand_files(big, ())

    assert len(kept) < count, "a tree over the argv budget is truncated"
    assert any("truncated" in record.message for record in caplog.records), (
        "truncation must be stated, not silent"
    )
